# Site settings
title: Meo Electric
email: hello@meoelectric.com
description: > # this means to ignore newlines until "baseurl:"
  Electrifying personal transportation in Canada.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.meoelectric.com" # the base hostname & protocol for your site
twitter_username: MeoElectric
github_username:  arirawr

# THEME-SPECIFIC CONFIGURATION
theme:
  title: Meo Electric
  avatar: avatar.png
  # Header and footer text
  header_text: >
     <p>My name is <strong>Ari</strong>. I'm a tech evangelist and consultant. I get really passionate about startups, hackathons, marketing, community, web development, and hedgehogs.</p>

     <p>Check out the links above to find me elsewhere on the web.</p>
  header_text_feature_image:
  footer_text: >
   Follow us on <a href="http://twitter.com/MeoElectric">Twitter</a> and <a href="http://facebook.com/MeoElectric">Facebook</a>

  # Icons
  rss: true
  email_address: "hello@meoelectric.com" # Full email address, e.g. "sam@example.com"
  facebook: "MeoElectric"
  github: "arirawr"
  instagram: "itsariari"
  linkedin: "http://linkedin.com/Meo-Electric"
  twitter: "MeoElectric"

  # Scripts
  google_analytics: "UA-64453343-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "blogariariio"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Join us on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Open+Sans:300italic,400italic,700italic,400,800,300,700"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 50
paginate_path: "/:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
